created Counter component
isdi-coders-202207-bcn-coding-adventure/lorena-martinez-front pull request #2
Opened 2022-08-22 11:53 UTC by MMLORENA

2022-08-22 12:46 UTC, mariogl requested changes

2022-08-22 12:46 UTC, mariogl commented on src/App.tsx
> +      <Counter />
¿Por qué está fuera del layout?

2022-08-22 12:46 UTC, mariogl commented on src/components/Counter/Counter.tsx
> +        <span className="counter-days__title ">days</span>
Esto no es el título del ítem.

2022-08-22 13:01 UTC, MMLORENA commented on src/App.tsx
> +      <Counter />
Corregido

2022-08-22 13:01 UTC, MMLORENA commented on src/components/Counter/Counter.tsx
> +        <span className="counter-days__title ">days</span>
Cierto

2022-08-22 13:25 UTC, mariogl requested changes

2022-08-22 13:25 UTC, mariogl commented on src/components/Counter/Counter.tsx
> +        <span className="counter-item__title ">days</span>
Insisto: esto no es un título.

2022-08-22 13:54 UTC, mariogl approved these changes
Fase 3: Dale estilos al componente contador (utiliza styled-components).

2022-08-22 13:56 UTC, merged

2022-08-24 16:10 UTC, Gax1 commented on src/components/Counter/Counter.tsx
> +export default Counter;
Me parece correcto la utilización de spans dentro de los li. Muy preciso

2022-08-24 16:30 UTC, MMLORENA commented on src/components/Counter/Counter.tsx
> +export default Counter;
gracias